export interface Issue {
  active_lock_reason: null;
  assignee: null;
  assignees: string[];
  author_association: string;
  body: string;
  closed_at: string | null;
  closed_by: string | null;
  comments: number;
  comments_url: string | null;
  created_at: string;
  draft: boolean;
  events_url: string;
  html_url: string;
  id: number;
  labels: object[];
  locked: boolean;
  milestone: null;
  node_id: string;
  number: number;
  performed_via_github_app: boolean | null;
  pull_request: object | null | object[];
  reactions: object[] | null | object;
  repository_url: string;
  state: string;
  state_reason: string | null;
  sub_issues_summary: object;
  timeline_url: string;
  title: string;
  updated_at: string;
  url: string;
  user: {
    avatar_url: string | null;
    events_url: string | null;
    followers_url: string | null;
    following_url: string | null;
    gists_url: string;
    gravatar_id: string | null;
    html_url: string;
    id: number;
    login: string;
    node_id: string;
    organizations_url: string | null;
    received_events_url: string | null;
    repos_url: string;
    site_admin: boolean;
    starred_url: string;
    subscriptions_url: string;
    type: string;
    url: string;
    user_view_type: string;
  };
}
